# Generated by Django 4.2 on 2023-12-18 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RdsInstanceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.CharField(help_text='实例id', max_length=255)),
                ('account', models.CharField(help_text='账号', max_length=255)),
                ('instanceType', models.CharField(help_text='实例类型', max_length=255)),
                ('instanceStatus', models.CharField(help_text='实例状态', max_length=255)),
                ('affiliation', models.CharField(help_text='所属', max_length=255)),
                ('affiliationData', models.CharField(help_text='所属数据', max_length=255)),
                ('accountDescription', models.CharField(help_text='账号描述', max_length=255)),
                ('characterSet', models.CharField(help_text='字符集', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RdsDatabaseResourceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(help_text='组织', max_length=255)),
                ('systemName', models.CharField(help_text='系统名称', max_length=255)),
                ('instanceId', models.CharField(help_text='实例id', max_length=255)),
                ('instanceIp', models.CharField(help_text='实例ip', max_length=255)),
                ('instanceName', models.CharField(help_text='实例名称', max_length=255)),
                ('internalNetworkAddress', models.CharField(help_text='内网地址', max_length=255)),
                ('port', models.IntegerField(help_text='端口号')),
                ('cpu', models.CharField(help_text='CPU核数', max_length=255)),
                ('diskSpace', models.CharField(help_text='磁盘空间', max_length=255)),
                ('memory', models.CharField(help_text='内存', max_length=255)),
                ('connectNumber', models.IntegerField(help_text='连接数')),
                ('IOPS', models.CharField(help_text='IOPS', max_length=255)),
                ('creationTime', models.DateTimeField(help_text='创建时间', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RdsDatabaseMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.CharField(help_text='实例id', max_length=255)),
                ('instanceName', models.CharField(help_text='实例名称', max_length=255)),
                ('cpuUtilization', models.CharField(help_text='cpu利用率', max_length=255)),
                ('memoryUtilization', models.CharField(help_text='内存利用率', max_length=255)),
                ('diskUtilization', models.CharField(help_text='硬盘利用率', max_length=255)),
                ('connectUtilization', models.CharField(help_text='连接利用率', max_length=255)),
                ('iopsUsage', models.CharField(help_text='IOPS使用率', max_length=255)),
                ('QPS', models.CharField(help_text='QPS', max_length=255)),
                ('networkIncomingTraffic', models.CharField(help_text='网络入流量', max_length=255)),
                ('networkOutTraffic', models.CharField(help_text='网络出流量', max_length=255)),
                ('mainBackupDelay', models.CharField(help_text='主备延迟', max_length=255)),
                ('activeStandbySwitching', models.CharField(help_text='主备切换', max_length=255)),
                ('numberOfTableLocks', models.CharField(help_text='表锁个数', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
