# Generated by Django 4.2 on 2023-05-31 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(help_text='业务系统名称', max_length=255)),
                ('project_name', models.CharField(help_text='项目名称', max_length=255)),
                ('framework_type', models.CharField(blank=True, help_text='架构类型', max_length=50, null=True)),
                ('project_type', models.CharField(blank=True, help_text='项目类别', max_length=50, null=True)),
                ('buz_org', models.CharField(blank=True, help_text='业务部门', max_length=100, null=True)),
            ],
            options={
                'db_table': 'architecture_review',
            },
        ),
        migrations.CreateModel(
            name='ArchitectureReviewModelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_submit_time', models.DateTimeField(blank=True, help_text='首次提报时间', null=True)),
                ('first_approval_time', models.DateTimeField(blank=True, help_text='首次审批时间', null=True)),
                ('submit_count', models.IntegerField(blank=True, help_text='提报次数', null=True)),
                ('last_submit_time', models.DateTimeField(blank=True, help_text='最后提报时间', null=True)),
                ('approval_pass_time', models.DateTimeField(blank=True, help_text='审批通过时间', null=True)),
                ('approval_opinion', models.CharField(blank=True, help_text='审批意见', max_length=50, null=True)),
                ('is_cloud', models.CharField(blank=True, help_text='是否上云', max_length=50, null=True)),
                ('cloud_time', models.DateTimeField(blank=True, help_text='上云时间', null=True)),
                ('deployment_time', models.DateTimeField(blank=True, help_text='实施部署时间', null=True)),
                ('owner_org_name', models.CharField(blank=True, help_text='建设单位', max_length=255, null=True)),
                ('owner_user_name', models.CharField(blank=True, help_text='建设单位负责人', max_length=50, null=True)),
                ('owner_user_tel', models.CharField(blank=True, help_text='建设单位负责人电话', max_length=20, null=True)),
                ('owner_user_email', models.CharField(blank=True, help_text='建设单位负责人邮箱', max_length=100, null=True)),
                ('buz_org_user_name', models.CharField(blank=True, help_text='业务部门负责人', max_length=100, null=True)),
                ('buz_org_user_tel', models.CharField(blank=True, help_text='业务部门负责人电话', max_length=100, null=True)),
                ('buz_org_user_mail', models.CharField(blank=True, help_text='业务部门负责人邮箱', max_length=100, null=True)),
                ('cons_org_name', models.CharField(blank=True, help_text='承建单位', max_length=100, null=True)),
                ('cons_user_name', models.CharField(blank=True, help_text='承建单位负责人', max_length=100, null=True)),
                ('cons_user_tel', models.CharField(blank=True, help_text='承建单位电话', max_length=100, null=True)),
                ('cons_user_mail', models.CharField(blank=True, help_text='承建单位邮箱', max_length=100, null=True)),
                ('pro_arc_rev', models.OneToOneField(help_text='一对一关系', on_delete=django.db.models.deletion.CASCADE, to='ArchitectureReview.architecturereviewmodel')),
            ],
            options={
                'db_table': 'architecture_review_detail',
            },
        ),
    ]
