# Generated by Django 4.2 on 2023-09-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArchitectureReview', '0002_user_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
