# Generated by Django 4.2 on 2023-08-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(help_text='组织的id值', max_length=255)),
                ('DepartmentName', models.CharField(help_text='组织名称', max_length=255)),
                ('ResourceGroup', models.CharField(help_text='资源集的id值', max_length=255)),
                ('ResourceGroupName', models.CharField(help_text='资源集名称', max_length=255)),
            ],
            options={
                'db_table': 'DepartmentResourceGroup',
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorizeType', models.CharField(help_text='认证类型', max_length=255)),
                ('namespaceStatus', models.CharField(help_text='命名空间状态', max_length=30)),
                ('namespaceName', models.CharField(help_text='命名空间名称', max_length=255)),
                ('defaultVisibility', models.CharField(help_text='默认仓库类型', max_length=255)),
                ('autoCreate', models.CharField(help_text='是否自动创建仓库', max_length=255)),
                ('depart_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NameSpace.departmentresourcegroup')),
            ],
            options={
                'db_table': 'Namespace',
            },
        ),
    ]
