# Generated by Django 4.2 on 2023-10-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dockerize', models.BooleanField(max_length=20, verbose_name='Dockerize')),
                ('BuildPackageId', models.IntegerField(verbose_name='BuildPackageId')),
                ('ClusterId', models.CharField(max_length=70, verbose_name='ClusterId')),
                ('Memory', models.IntegerField(verbose_name='Memory')),
                ('Port', models.IntegerField(verbose_name='Port')),
                ('CreateTime', models.CharField(max_length=70, verbose_name='CreateTime')),
                ('Cpu', models.IntegerField(verbose_name='Cpu')),
                ('ClusterType', models.CharField(choices=[(5, '容器服务K8S集群'), (2, 'ECS集群')], max_length=30, verbose_name='集群类型')),
                ('Name', models.CharField(max_length=100, verbose_name='应用名')),
                ('InstanceCount', models.IntegerField(verbose_name='实例总数')),
                ('ApplicationType', models.CharField(max_length=200, null=True, verbose_name='ApplicationType')),
                ('AppId', models.CharField(max_length=200, verbose_name='app id')),
                ('RegionId', models.CharField(max_length=200, verbose_name='RegionId')),
                ('RunningInstanceCount', models.IntegerField(verbose_name='RunningInstanceCount')),
            ],
        ),
    ]
