# Generated by Django 4.2 on 2023-10-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInstance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appinstancemodel',
            table='app_instance',
        ),
    ]
