# Generated by Django 4.2 on 2023-08-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRepository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
