# Generated by Django 4.2 on 2023-08-14 07:21

import APPS.ProjectManage.ImageRepository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRepository', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=APPS.ProjectManage.ImageRepository.models.custom_upload_to),
        ),
    ]
