# Generated by Django 4.2 on 2023-09-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRepository', '0004_alter_file_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerepomodel',
            old_name='create_time',
            new_name='gmtModified',
        ),
        migrations.RenameField(
            model_name='imagerepomodel',
            old_name='project_name',
            new_name='repoAuthorizeType',
        ),
        migrations.RenameField(
            model_name='imagerepomodel',
            old_name='repo_name',
            new_name='repoName',
        ),
        migrations.RenameField(
            model_name='imagerepomodel',
            old_name='repo_permission',
            new_name='repoNamespace',
        ),
        migrations.RenameField(
            model_name='imagerepomodel',
            old_name='repo_status',
            new_name='repoStatus',
        ),
        migrations.RenameField(
            model_name='imagerepomodel',
            old_name='repo_type',
            new_name='repoType',
        ),
        migrations.RenameField(
            model_name='imagerepomodel',
            old_name='repo_url',
            new_name='repoUrl',
        ),
        migrations.AddField(
            model_name='imagerepomodel',
            name='repoId',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
