# Generated by Django 4.2 on 2023-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRepository', '0005_rename_create_time_imagerepomodel_gmtmodified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerepomodel',
            name='gmtModified',
            field=models.CharField(max_length=255),
        ),
    ]
