# Generated by Django 3.2.13 on 2023-09-08 12:17

import APPS.ProjectManage.ImageRepository.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageRepository', '0006_alter_imagerepomodel_gmtmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=APPS.ProjectManage.ImageRepository.models.custom_upload_to),
        ),
    ]
