# Generated by Django 4.2 on 2023-10-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '收获地址表'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '地区表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '验证码表'},
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='verifycode',
            table='verifycode',
        ),
    ]
