# Generated by Django 4.2 on 2023-09-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployBuildModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jarBuildName', models.CharField(max_length=255)),
                ('jarBuildNameSpace', models.CharField(max_length=255)),
                ('jarBuildRepo', models.CharField(max_length=255)),
                ('jarBuildVersion', models.CharField(max_length=255)),
                ('jarBuildCommand', models.CharField(max_length=255)),
                ('jarBuildTime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'DeployBuild',
            },
        ),
    ]
