# Generated by Django 4.2 on 2023-09-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeploymentBuild', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploybuildmodel',
            name='jarBuildCommand',
            field=models.TextField(),
        ),
    ]
