# Generated by Django 4.2 on 2023-09-22 08:31

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeploymentBuild', '0003_deploybuildfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploybuildmodel',
            name='jarBuildReturnCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploybuildmodel',
            name='jarBuildStderr',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deploybuildmodel',
            name='jarBuildStdout',
            field=models.TextField(default=builtins.print),
            preserve_default=False,
        ),
    ]
